In [49]:
import torch
import numpy as np

In [50]:
data=[[1,2],[3,4]]
x_data= torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [51]:
arr=np.array(data)
arr

array([[1, 2],
       [3, 4]])

In [52]:
x=torch.from_numpy(arr)
x

tensor([[1, 2],
        [3, 4]])

In [53]:
x_ones= torch.ones_like(x)
x_ones

tensor([[1, 1],
        [1, 1]])

In [54]:
x_zeros= torch.zeros_like(x)
x_zeros

tensor([[0, 0],
        [0, 0]])

In [55]:
x_rand= torch.rand_like(x, dtype=torch.float)
x_rand

tensor([[0.8476, 0.8892],
        [0.5125, 0.9388]])

In [56]:
rand_tensor= torch.rand(2,3)
rand_tensor

tensor([[0.8396, 0.9960, 0.4393],
        [0.6289, 0.0821, 0.5851]])

In [57]:
ones_tensor= torch.ones(2,3, dtype=torch.float32)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [58]:
zeros_tensor= torch.zeros(2,3)
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [59]:
rand_tensor.shape

torch.Size([2, 3])

In [60]:
rand_tensor.dtype

torch.float32

In [61]:
rand_tensor.device

device(type='cpu')

In [62]:
if torch.cuda.is_available():
    rand_tensor = rand_tensor.to('cuda')

In [63]:
 rand_tensor

tensor([[0.8396, 0.9960, 0.4393],
        [0.6289, 0.0821, 0.5851]])

In [64]:
rand_tensor.device

device(type='cpu')

In [65]:
rand_tensor[:,1]=1
rand_tensor

tensor([[0.8396, 1.0000, 0.4393],
        [0.6289, 1.0000, 0.5851]])

In [66]:
rand_tensor[0]

tensor([0.8396, 1.0000, 0.4393])

In [67]:
rand_tensor[:,0]

tensor([0.8396, 0.6289])

In [68]:
rand_tensor[...,-1]

tensor([0.4393, 0.5851])

In [69]:
rand_tensor.sum()

tensor(4.4930)

In [70]:
rand_tensor.sum().item()

4.493006229400635

In [71]:
t1= torch.cat([rand_tensor, zeros_tensor],dim=1)
t1

tensor([[0.8396, 1.0000, 0.4393, 0.0000, 0.0000, 0.0000],
        [0.6289, 1.0000, 0.5851, 0.0000, 0.0000, 0.0000]])

In [72]:
t2= torch.cat([rand_tensor, zeros_tensor],dim=0)
t2

tensor([[0.8396, 1.0000, 0.4393],
        [0.6289, 1.0000, 0.5851],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])

In [73]:
rand_tensor.mul(ones_tensor)

tensor([[0.8396, 1.0000, 0.4393],
        [0.6289, 1.0000, 0.5851]])

In [74]:
rand_tensor.matmul(rand_tensor.T)

tensor([[1.8980, 1.7851],
        [1.7851, 1.7379]])

In [75]:
rand_tensor.add_(5)

tensor([[5.8396, 6.0000, 5.4393],
        [5.6289, 6.0000, 5.5851]])

In [76]:
n= np.ones(5)
n

array([1., 1., 1., 1., 1.])

In [77]:
t=torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [78]:
t.add_(1)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [79]:
x = torch.empty(1)
print(x)

tensor([-3.6637e+17])


In [80]:
x.size()

torch.Size([1])

In [81]:
x = torch.empty(2,3)
print(x)

tensor([[-4.5026e+14,  3.1668e-41, -3.6493e+17],
        [ 3.1668e-41,  1.0000e+00,  5.8512e-01]])


In [82]:
torch.empty(2,2,3)

tensor([[[-2.9833e-36,  7.0065e-45,  0.0000e+00],
         [ 1.5982e-05,  0.0000e+00,  2.9652e+02]],

        [[ 0.0000e+00,  1.5982e-05,  0.0000e+00],
         [ 1.8750e+00, -3.6893e+19,  1.7713e+00]]])

In [83]:
y=x.view(6)
y

tensor([-4.5026e+14,  3.1668e-41, -3.6493e+17,  3.1668e-41,  1.0000e+00,
         5.8512e-01])

In [84]:
z=x.view(1,-1)
z

tensor([[-4.5026e+14,  3.1668e-41, -3.6493e+17,  3.1668e-41,  1.0000e+00,
          5.8512e-01]])

In [85]:
a= torch.ones(2,2)
b= torch.ones(2,2)
a,b

(tensor([[1., 1.],
         [1., 1.]]),
 tensor([[1., 1.],
         [1., 1.]]))

In [86]:
a+b

tensor([[2., 2.],
        [2., 2.]])

In [87]:
a-b

tensor([[0., 0.],
        [0., 0.]])

In [88]:
a*b

tensor([[1., 1.],
        [1., 1.]])

In [89]:
a/b

tensor([[1., 1.],
        [1., 1.]])

In [90]:
a[1,1].item()

1.0

In [91]:
torch.full((2,3),50)

tensor([[50, 50, 50],
        [50, 50, 50]])