In [25]:
import numpy as np
array = np.array([1, 2, 3, 4, 5])
print(array)
print(type(array))
print(array[0])
print(array[2] + array[3])


[1 2 3 4 5]
<class 'numpy.ndarray'>
1
7
10
7
[[ 6  7  8  9 10]]
6
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


In [46]:
#3D array

arr1 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr1[0, 1, 2])
print (arr1.shape)
arr2= arr1.reshape(4, 3)
print (arr2)
arr2= arr1.reshape(1,12)
print (arr2)
print (arr1.dtype)
arr1 = np.array([[["asif","adnan"], ["khairul","sadid"]], [["tithy","tanisha"], ["alvi", "partho"]]])
print (arr1.dtype)
x = np.where(arr1 == "tithi")
print(x)

6
(2, 2, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
int64
<U7
(array([], dtype=int64), array([], dtype=int64), array([], dtype=int64))


In [42]:

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
y = arr.view()
print (arr)
print (x)
print (y)
print ("\n\nbase fuction\n\n")
print (x.base)
print (y.base)
print ("\n\nJoining\n\n")
arr1 = np.array(["Asif","Adnan"])

arr2 = np.array(["Khairul","tithi","sadid"])
x = np.where(arr2 == "tithi")
print(x)
arr = np.concatenate((arr1, arr2))

print(arr)

[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]


base fuction


None
[42  2  3  4  5]


Joining


(array([1]),)
['Asif' 'Adnan' 'Khairul' 'tithi' 'sadid']


In [29]:
#2D array

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print( arr[-1, -1])
print( arr[1, 1])
print(arr[1:5])
print (arr.shape)
arr1= arr.reshape(2, 5)
print (arr1)
arr2= arr.reshape(1,10)
print (arr2)

10
7
[[ 6  7  8  9 10]]
(2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5  6  7  8  9 10]]
